name: 'Bayan'

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installing dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: 
          sudo apt-get update -y;
          sudo apt-get install -y libboost-all-dev

      - name: Installing dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install boost-program-options boost-filesystem boost-crc boost-regex --triplet x64-windows

      - name: Configure Cmake (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cmake -B build -G "Unix Makefiles"

      - name: Configure Cmake (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build project and package
        run: cmake --build build --target package --config Release
          
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ext: ${{
            matrix.os == 'ubuntu-latest' && '.tar.gz' ||
            matrix.os == 'windows-latest' && '.zip'}}
        shell: bash
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          if gh release view "${TAG}" > /dev/null 2>&1; 
          then gh release upload "${TAG}" bin/bayan${ext};
          else gh release create "${TAG}" bin/bayan${ext};
          fi